name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install linux dependencies
        run: sudo apt-get update && sudo apt-get install -y libudev-dev libusb-1.0-0-dev
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - uses: actions/setup-node@main
        with:
          node-version: 12.x
      - name: get yarn cache
        if: always() && job.status != 'cancelled'
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        if: always() && job.status != 'cancelled'
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: install dependencies
        run: yarn install --production
      - name: test
        run: yarn test
      - name: test  no git diff
        run: yarn test-no-git-diff
      - name: codecov
        run: npx codecov